### ISSUE TITLE
Minified version

### ISSUE THREAD

**Issue by ghost** [shaack/bootstrap-show-modal#4]
This is really useful, thank you. Any chance of a minified version? :)
Same goes for bootstrap-input-spinner.

**Comment by shaack** [comment]
I thought it should be up to the using programmer to create minified versions, because all the script sources you are using should also be concatenated to one file.
But it is easy to create your minified version with uglify: https://www.npmjs.com/package/uglify-js 
Just: 
`npm install uglify-js -g` 
and then in the src-folder
`uglifyjs bootstrap-show-modal.js  --compress --mangle > bootstrap-show-modal.min.js`

**Comment by ghost** [comment]
It works, thank you!

**Comment by shaack** [comment]
Thanks for the feedback! I think I will add these instructions to the README.
