### ISSUE TITLE
Not working with webpack

### ISSUE THREAD

**Issue by jamesj2** [shaack/bootstrap-show-modal#8]
I tried upgrading to bootstrap-show-modal v1.1.19 and it no longer works when using webpack.  I reverted back to v1.1.18 it works.  

Relevant sections of my webpack config.
```
plugins: [
    new webpack.ProvidePlugin({
      $: "jquery",
      jQuery: "jquery",
      "window.jQuery":"jquery" 
      })
]
```

```
  module: {
    rules: [{
        test: require.resolve("jquery"),
        use: [
          {
            loader: "expose-loader",
            options: "jQuery"
          },
          {
            loader: "expose-loader",
            options: "$"
          }
        ]
      }]
  }
```

**Comment by shaack** [comment]
v1.1.19 is just an update of the dependencies because of a security issue in (as far as I remenber) jQuery. https://github.com/shaack/bootstrap-show-modal/commit/0406ff7c716749aa3d7e41a071b9b7c6074a06bb Nothing was changed in bootstrap-show-modal. Therefor this issue seems to be more a Webpack, bootstrap or jQuery issue. Maybe you just need to upgrade Webpack.

**Comment by shaack** [comment]
See also: https://github.com/webpack/webpack/issues/10705#issuecomment-613787137 
"jQuery 3.5.0 with Webpack may be your issue."

**Comment by jamesj2** [comment]
I tried the work around you suggested and it didn't fix my issue.  I did notice a node_modules folder containing jquery inside the bootstrap-show-modal directory when installing v1.1.19.  So I ran `npm dedupe` and it removed the extra jquery and it fixed the issue.
